root: 
  cwd: './'
  path: '/@'

meta: 
  lang: en
  name: bend.ui
  title: WebUI Kit & Design System

navs:
  header:
    main:
      - link: '/'
        title: Design
      - link: '/build'
        title: Build
      - link: '/experience'
        title: Experience
      - link: '/docs'
        title: Docs
      - link: '#'
        title: Play
        class: hidden bg-primary text-secondary font-semibold px-6 py-2 rounded-full drop-shadow md:block hover:bg-indigo-700 transition
    search:
      placeholder: Search...

  aside:
    - group: getting-started
      items:
        - introduction
        - file-structure
        - build-tools
    - group: components
      items:
        - alerts
        - buttons
        - dropdowns
        - forms
        - input-group
    - group: plugins
      items:
        - drawer
        - show-hide-password
  
socials:
  - platform: Github
    icon: github
    link: https://github.com/ilkergonenc/io.play
  # - platform: Dribbble
  #   icon: dribbble
  #   link: '#'
  # - platform: Behance
  #   icon: behance
  #   link: '#'
  # - platform: Instagram
  #   icon: instagram
  #   link: '#'
