root: 
  cwd: './'
  path: '/@/docs'

meta: 
  lang: en
  name: play.io
  title: Static WebUI Renderr

navs:
  header:
    main:
      # - link: '/'
      #   title: Home
      # - link: '/docs'
      #   title: Docs
      - link: '/components'
        title: Components
      # - link: '#'
      #   title: Downloads
      #   class: hidden bg-slate-800 text-slate-100 px-4 py-2 rounded-full md:block
    search:
      placeholder: Search...

  accordion:
    - group: foundation
      items:
        - frames
        - surfaces
        - elavation
        - navigations
        - layouts
    - group: design
      items:
        - colors
        - typography
    - group: components
      items:
        - cards
        - buttons
        - callouts
        - dropdown
        - collapse
        - accordion
        - tabs
        - boards
        - offCanvas
        - tooltips

  aside:

    - title: Foundation
      href: /docs/components
      class: heading font-semibold pl-0

    - title: Frames
      href: /docs/content/typography
    - title: Surfaces
      href: /docs/content/typography
    - title: Elavation
      href: /docs/content/typography
    - title: Navigations
      href: /docs/components/navs

    - title: Content
      href: /docs/components/navs
      class: heading font-semibold pl-0

    - title: Typography
      href: /docs/content/typography
    - title: Media
      href: /docs/content/typography
    - title: Tables
      href: /docs/content/typography

    - title: Components
      href: /docs/components
      class: heading font-semibold pl-0

    - title: Buttons
      href: /docs/components/buttons
    - title: Forms
      href: /docs/components/buttons
    - title: Cards
      href: /docs/components/cards
    - title: Callouts
      href: /docs/components/callouts
    - title: Boards
      href: /docs/components/boards
    - title: Tooltips
      href: /docs/components/tooltips

    - title: Transitions
      href: /docs/components
      class: heading font-semibold pl-0
      
    - title: Dropdown
      href: /docs/components/dropdown
    - title: Collapse
      href: /docs/components/collapse
    - title: Accordion
      href: /docs/components/accordion
    - title: OffCanvas
      href: /docs/components/offcanvas
    - title: Tabs
      href: /docs/components/tabs
  
socials:
  - platform: Github
    icon: github
    link: https://github.com/ilkergonenc/io.play
  - platform: Dribbble
    icon: dribbble
    link: '#'
  - platform: Behance
    icon: behance
    link: '#'
  - platform: Instagram
    icon: instagram
    link: '#'
