root: 
  cwd: '.'

meta: 
  lang: en
  name: play.io
  title: Static WebUI Renderr

navs:
  header:
    main:
      - link: '/'
        title: Home
      - link: '/docs'
        title: Docs
      - link: '#'
        title: Examples
      - link: '#'
        title: Downloads
        class: bg-slate-800 text-slate-100 px-4 py-2 rounded-full
    search:
      placeholder: Search...

  aside:
    - group: getting-started
      items:
        - introduction
        - file-structure
        - build-tools
    - group: components
      items:
        - alerts
        - buttons
        - dropdowns
        - forms
        - input-group
    - group: plugins
      items:
        - drawer
        - show-hide-password
  
socials:
  - platform: Githubc
    icon: github
    link: '#'
  - platform: Dribbble
    icon: dribbble
    link: '#'
  - platform: Behance
    icon: behance
    link: '#'
  - platform: Instagram
    icon: instagram
    link: '#'
