root: 
  cwd: './'
  path: '/@/docs'

meta: 
  lang: en
  name: play.io
  title: Static WebUI Renderr

navs:
  header:
    main:
      # - link: '/'
      #   title: Home
      # - link: '/docs'
      #   title: Docs
      - link: '/components'
        title: Components
      # - link: '#'
      #   title: Downloads
      #   class: hidden bg-slate-800 text-slate-100 px-4 py-2 rounded-full md:block
    search:
      placeholder: Search...

  accordion:
    - group: foundation
      items:
        - frames
        - surfaces
        - elavation
        - navigations
        - layouts
    - group: design
      items:
        - colors
        - typography
    - group: components
      items:
        - cards
        - buttons
        - callouts
        - dropdown
        - collapse
        - accordion
        - tabs
        - boards
        - offCanvas
        - tooltips
    - group: plugins
      items:
        - highlight
        - clipboard
        - tocmenu
        - search
  
socials:
  - platform: Github
    icon: github
    link: https://github.com/ilkergonenc/io.play
  - platform: Dribbble
    icon: dribbble
    link: '#'
  - platform: Behance
    icon: behance
    link: '#'
  - platform: Instagram
    icon: instagram
    link: '#'
