root: 
  cwd: './'
  path: '/@/docs'

meta: 
  lang: en
  name: play.io
  title: Static WebUI Renderr

navs:
  header:
    main:
      # - link: '/'
      #   title: Home
      # - link: '/docs'
      #   title: Docs
      - link: '/components'
        title: Components
      # - link: '#'
      #   title: Downloads
      #   class: hidden bg-slate-800 text-slate-100 px-4 py-2 rounded-full md:block
    search:
      placeholder: Search...

  accordion:
    - group: getting-started
      items:
        - introduction
        - build-tools
    - group: foundation
      items:
        - surface
        - elevation
        - layout
        - color
        - typography
        - navigation

    - group: components
      items:
        - cards
        - buttons
        - callouts
        - dropdown
        - collapse
        - accordion
        - tabs
        - boards
        - offCanvas
        - tooltips
    # - group: plugins
    #   items:
    #     - highlight
    #     - clipboard
    #     - anchor
    #     - toc
    #     - search
    # - group: utilities
    #   items:
    #     - customization
  
socials:
  - platform: Github
    icon: github
    link: https://github.com/ilkergonenc/io.play
  - platform: Dribbble
    icon: dribbble
    link: '#'
  - platform: Behance
    icon: behance
    link: '#'
  - platform: Instagram
    icon: instagram
    link: '#'
