root: 
  cwd: './'
  path: '/@/docs'

meta: 
  lang: en
  name: play.io
  title: Static WebUI Renderr

navs:
  main:
    - title: bend
      href: '/@'
    - title: docs
      href: '/@/docs'
    # - title: ui|kit
    #   href: '/@/docs'

  accordion:
    - group: start-here
      items:
        - introduction
        - build-tools
    - group: foundation
      items:
        - surface
        - elevation
        - light
        - color
        - typography
        - layout
        - navigation
        - notification

    - group: components
      items:
        - cards
        - buttons
        - callouts
        - dropdown
        - collapse
        - accordion
        - tabs
        - lists
        - boards
        - offCanvas
        - tooltips
    # - group: plugins
    #   items:
    #     - highlight
    #     - clipboard
    #     - anchor
    #     - toc
    #     - search
    - group: utilities
      items:
        - customization
    - group: about
      items:
        - design system
  
socials:
  - platform: Github
    icon: github
    link: https://github.com/ilkergonenc/io.play
  - platform: Dribbble
    icon: dribbble
    link: '#'
  - platform: Behance
    icon: behance
    link: '#'
  - platform: Instagram
    icon: instagram
    link: '#'
